# Site settings
title: Nemo's Blog                                 # 博客的标题
SEOTitle: Captain Nemo的博客 | Captain Nemo's Blog          # 搜索的时候，显示在浏览器上的标题
header-img: img/post-bg-desk.jpg                   # 显示在首页的背景图片
email: yvonwrong@gmail.com                         # 邮箱
description: "Captain Nemo's Blog"  # 网站介绍
keyword: "AI, Machine Learning, Deep Learning, Computer vision, Python, C++"     # 关键词
url: "http://scottwyh.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog',这个不用填写
github_repo: "https://github.com/scottwyh/scottwyh.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.是否开启侧边栏
sidebar-about-description: "More efforts, more fortunes!"
sidebar-avatar: /img/about-Nemo-a.jpg      # 个人头像 use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
zhihu_username:        LEYM2
# github_username:     LEYM
weibo_username:       3874115079
# wechat_username:       LEYM
# douban_username:     LEYM
facebook_username:     LEYM
jianshu_username:    05c8324cee76
# twitter_username:    LEYM




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: e5424aa41bc0d34ced25                            #生成的clientID
  clientSecret: c53c6e3d6cb935a50a68bf9b08612ff1234e7ed2    #生成的clientSecret
  repo: scottwyh.github.io    #仓库名称
  owner: scottwyh    #github用户名
  admin: scottwyh
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: c3a06203eefcfd1d143ba2a23a896845

# Google Analytics
ga_track_id: 'UA-134758375-1'            # Format: UA-xxxxxx-xx
ga_domain: wahz.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Kaggle",
        href: "https://www.kaggle.com/"
    },{
        title: "天池AI",
        href: "https://tianchi.aliyun.com/home/"
    },{
        title: "Stanford",
        href: "https://online.stanford.edu/courses"
    }   
]
